# Generated by Django 5.0.3 on 2024-12-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='banner_image')),
                ('status', models.BooleanField(default=True)),
                ('banner_title', models.TextField(null=True)),
                ('banner_description', models.TextField(null=True)),
                ('banner_link', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255)),
                ('site_description', models.TextField()),
                ('site_keywords', models.CharField(max_length=255)),
                ('site_email', models.EmailField(max_length=254)),
                ('site_phone', models.CharField(max_length=20)),
                ('site_address', models.CharField(max_length=255)),
                ('site_logo', models.ImageField(upload_to='site_logo')),
                ('site_favicon', models.ImageField(upload_to='site_favicon')),
                ('site_color', models.CharField(max_length=255)),
                ('site_font', models.CharField(max_length=255)),
                ('site_background', models.CharField(max_length=255)),
                ('site_copyright', models.CharField(max_length=255)),
                ('site_time_zone', models.CharField(max_length=255)),
                ('site_currency', models.CharField(max_length=20)),
                ('site_language', models.CharField(max_length=20)),
                ('site_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
